package com.ddscanner.entities;

public enum ActivityTypes {

    DIVE_SPOT_ADDED, DIVE_SPOT_PHOTOS_ADDED, DIVE_SPOT_CHANGED, DIVE_SPOT_CHECKIN,
    DIVE_SPOT_REVIEW_ADDED, ACHIEVEMENT_GETTED, DIVE_SPOT_REVIEW_LIKE, DIVE_SPOT_REVIEW_DISLIKE,
    DIVE_SPOT_PHOTO_LIKE, DIVE_CENTER_INSTRUCTOR_REMOVE, DIVE_CENTER_INSTRUCTOR_ADD

}
